definitions:
  authPkg.AuthV0Request:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  authPkg.AuthV0Response:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  changePasswordPkg.ChangePasswordV0Request:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  changePasswordPkg.ChangePasswordV0Response:
    type: object
  checkEmailPkg.CheckEmailV0Request:
    properties:
      email:
        type: string
    type: object
  checkEmailPkg.CheckEmailV0Response:
    properties:
      isExists:
        type: boolean
    type: object
  getUserInfoPkg.GetUserInfoV0Response:
    properties:
      dateBirth:
        type: string
      email:
        type: string
      height:
        type: number
      id:
        type: string
      name:
        type: string
      patronymic:
        type: string
      sex:
        $ref: '#/definitions/pkg.Sex'
      surname:
        type: string
      weight:
        type: number
    type: object
  pkg.Sex:
    enum:
    - male
    - female
    type: string
    x-enum-varnames:
    - Male
    - Female
  registrationPkg.RegistrationV0Request:
    properties:
      dateBirth:
        type: string
      email:
        type: string
      height:
        type: number
      name:
        type: string
      password:
        type: string
      patronymic:
        type: string
      sex:
        $ref: '#/definitions/pkg.Sex'
      surname:
        type: string
      weight:
        type: number
    type: object
  registrationPkg.RegistrationV0Response:
    properties:
      id:
        type: string
    type: object
  updateInfoPkg.UpdateUserInfoV0Request:
    properties:
      dateBirth:
        type: string
      height:
        type: number
      name:
        type: string
      patronymic:
        type: string
      sex:
        $ref: '#/definitions/pkg.Sex'
      surname:
        type: string
      weight:
        type: number
    type: object
  updateInfoPkg.UpdateUserInfoV0Response:
    properties:
      dateBirth:
        type: string
      email:
        type: string
      height:
        type: number
      name:
        type: string
      patronymic:
        type: string
      sex:
        $ref: '#/definitions/pkg.Sex'
      surname:
        type: string
      weight:
        type: number
    type: object
  usecase.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/authPkg.AuthV0Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authPkg.AuthV0Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Аутентификация пользователей
      tags:
      - users
  /api/user/changePassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: JWT access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Refresh token cookie
        in: header
        name: Cookie
        required: true
        type: string
      - description: request
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/changePasswordPkg.ChangePasswordV0Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/changePasswordPkg.ChangePasswordV0Response'
        "400":
          description: Bad Request
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "404":
          description: Not Found
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Смена пароля
      tags:
      - users
  /api/user/checkEmail:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/checkEmailPkg.CheckEmailV0Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/checkEmailPkg.CheckEmailV0Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Проверка на существование пользователя с указанной почтой
      tags:
      - users
  /api/user/me:
    get:
      consumes:
      - application/json
      parameters:
      - description: JWT access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Refresh token cookie
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/getUserInfoPkg.GetUserInfoV0Response'
        "404":
          description: Not Found
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Получение информации о пользователе
      tags:
      - users
  /api/user/reg:
    post:
      consumes:
      - application/json
      parameters:
      - description: request
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/registrationPkg.RegistrationV0Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/registrationPkg.RegistrationV0Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Регистрация пользователей
      tags:
      - users
  /api/user/updateInfo:
    post:
      consumes:
      - application/json
      parameters:
      - description: JWT access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Refresh token cookie
        in: header
        name: Cookie
        required: true
        type: string
      - description: request
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/updateInfoPkg.UpdateUserInfoV0Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/updateInfoPkg.UpdateUserInfoV0Response'
        "400":
          description: Bad Request
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
        "500":
          description: Internal Server Error
          headers:
            accessToken:
              description: Новый access token
              type: string
            refreshToken:
              description: Новый refresh token
              type: string
          schema:
            $ref: '#/definitions/usecase.ErrorResponse'
      summary: Обновление информации о пользователе
      tags:
      - users
swagger: "2.0"
